### PR TITLE
Update aarch64 unrar binary

### PR DESCRIPTION
**Pull request by MichaIng**
The existing binary is a 32-bit ARM one, which for some reason stopped working on aarch64 systems with Debian. This commit replaced it with a recent actual aarch64 binary.

Source code: https://www.rarlab.com/rar/unrarsrc-6.1.7.tar.gz
Compiled on Debian Buster with GNU C v2.28 and C++ v8.3, hence bein the oldest guaranteed supported versions for this binary.

Solves: https://github.com/morpheus65535/bazarr/issues/1908

To reproduce the binary on an `aarch64` Debian Buster system:
```sh
sudo apt install g++ make
cd /tmp
curl -O https://www.rarlab.com/rar/unrarsrc-6.1.7.tar.gz
tar xf unrarsrc-6.1.7.tar.gz
rm unrarsrc-6.1.7.tar.gz
cd unrar
make
ls -l unrar
```

### CODE REVIEW

**Comment by MichaIng** [comment]
Ah, not an issue with the GNU C/C++ versions, GNU C v2.17 and sufficiently old GNU C++ etc seem to be sufficient, if I interpret the `readelf` output correctly:
```
Version needs section '.gnu.version_r' contains 4 entries:
 Addr: 0x0000000000001540  Offset: 0x001540  Link: 6 (.dynstr)
  000000: Version: 1  File: libgcc_s.so.1  Cnt: 1
  0x0010:   Name: GCC_3.0  Flags: none  Version: 8
  0x0020: Version: 1  File: libpthread.so.0  Cnt: 1
  0x0030:   Name: GLIBC_2.17  Flags: none  Version: 4
  0x0040: Version: 1  File: libc.so.6  Cnt: 1
  0x0050:   Name: GLIBC_2.17  Flags: none  Version: 3
  0x0060: Version: 1  File: libstdc++.so.6  Cnt: 4
  0x0070:   Name: CXXABI_1.3.8  Flags: none  Version: 7
  0x0080:   Name: CXXABI_1.3.9  Flags: none  Version: 6
  0x0090:   Name: CXXABI_1.3  Flags: none  Version: 5
  0x00a0:   Name: GLIBCXX_3.4  Flags: none  Version: 2

Displaying notes found in: .note.ABI-tag
  Owner                 Data size       Description
  GNU                  0x00000010       NT_GNU_ABI_TAG (ABI version tag)
    OS: Linux, ABI: 3.7.0
```

And Bazarr requires Python 3.7 (>=Buster) anyway.

**Comment by morpheus65535** [comment]
You also need to edit this file: https://github.com/morpheus65535/bazarr/blob/development/bazarr/utilities/binaries.json

**Comment by MichaIng** [comment]
Companion PR is up: https://github.com/morpheus65535/bazarr/pull/1912

**Comment by morpheus65535** [comment]
Thanks! I'll merge this just before releasing 1.1.1 to prevent new installation of 1.1.0 not being able to get the binary with the proper hash.

**Pull request merged**
